apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "external-citytool.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- with .Values.certIssuer }}
    cert-manager.io/issuer: {{ . | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - backend: 
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
            pathType: Prefix
            path: /
  tls:
  - hosts:
    - {{ .Values.host | quote }}
    secretName: {{ .Values.host }}-tls
